# Generated by Django 3.1.2 on 2020-11-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201105_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.productvendordetails'),
        ),
    ]
