# Generated by Django 3.1.3 on 2020-11-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201120_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_registered_prices',
        ),
        migrations.AddField(
            model_name='productvendordetails',
            name='registered_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default=dict),
        ),
    ]
