# Generated by Django 3.1.3 on 2020-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201125_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='css_selectors',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='filter',
            name='characteristics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default=dict),
        ),
    ]
