# Generated by Django 3.1.3 on 2020-11-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201126_1657'),
        ('app', '0005_auto_20201127_0204'),
    ]

    operations = [
    ]
