# Generated by Django 3.1.3 on 2020-11-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20201127_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvendordetails',
            name='unit_price',
        ),
    ]
