# Generated by Django 3.1.2 on 2020-12-08 20:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201128_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='filter',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
    ]
