# Generated by Django 3.1.3 on 2021-01-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_minimum_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvendordetails',
            old_name='url',
            new_name='product_url',
        ),
        migrations.RenameField(
            model_name='starturl',
            old_name='url',
            new_name='start_url',
        ),
    ]
