# Generated by Django 3.1.6 on 2021-02-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210101_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='isActive',
        ),
    ]
