# Generated by Django 3.1.3 on 2021-05-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starturl',
            name='item',
        ),
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
